import IMAGES from "./assets/images/Images"

const data = [
  {
    id: 1,
    imageUrl: IMAGES.bigmac,
    product: "Big Mac",
    count: 0,
    cost: 2,
  },
  {
    id: 2,
    imageUrl: IMAGES.flipflops,
    product: "flipflops",
    count: 0,
    cost: 3,
  },
  {
    id: 3,
    imageUrl: IMAGES.cocacola,
    product: "Coca Cola Pack",
    count: 0,
    cost: 5,
  },
  {
    id: 4,
    imageUrl: IMAGES.movieticket,
    product: "Movie Ticket",
    count: 0,
    cost: 12,
  },
  {
    id: 5,
    imageUrl: IMAGES.book,
    product: "Book",
    count: 0,
    cost: 15,
  },
  {
    id: 6,
    imageUrl: IMAGES.lobsterdinner,
    product: "Lobster Dinner",
    count: 0,
    cost: 45,
  },
  {
    id: 7,
    imageUrl: IMAGES.videogame,
    product: "Video Game",
    count: 0,
    cost: 60,
  },
  {
    id: 8,
    imageUrl: IMAGES.amazonecho,
    product: "Amazon Echo",
    count: 0,
    cost: 99,
  },
  {
    id: 9,
    imageUrl: IMAGES.yearofnetflix,
    product: "Year of Netflix",
    count: 0,
    cost: 100,
  },
  {
    id: 10,
    imageUrl: IMAGES.airjordans,
    product: "Air Jordans",
    count: 0,
    cost: 125,
  },
  {
    id: 11,
    imageUrl: IMAGES.airpods,
    product: "Airpods",
    count: 0,
    cost: 199,
  },
  {
    id: 12,
    imageUrl: IMAGES.gaming,
    product: "Gaming Console",
    count: 0,
    cost: 299,
  },
  {
    id: 13,
    imageUrl: IMAGES.drone,
    product: "Drone",
    count: 0,
    cost: 350,
  },
  {
    id: 14,
    imageUrl: IMAGES.smartphone,
    product: "Smartphone",
    count: 0,
    cost: 699,
  },
  {
    id: 15,
    imageUrl: IMAGES.bike,
    product: "Bike",
    count: 0,
    cost: 800,
  },
  {
    id: 16,
    imageUrl: IMAGES.kitten,
    product: "Kitten",
    count: 0,
    cost: 1_500,
  },
  {
    id: 17,
    imageUrl: IMAGES.puppy,
    product: "Puppy",
    count: 0,
    cost: 1_500,
  },
  {
    id: 18,
    imageUrl: IMAGES.autorickshaw,
    product: "Auto Ricksaw",
    count: 0,
    cost: 2_300,
  },
  {
    id: 19,
    imageUrl: IMAGES.horse,
    product: "Horse",
    count: 0,
    cost: 2_500,
  },
  {
    id: 20,
    imageUrl: IMAGES.acreofarmland,
    product: "Acre of Farmland",
    count: 0,
    cost: 3_000,
  },
  {
    id: 21,
    imageUrl: IMAGES.handbag,
    product: "Designer Handbag",
    count: 0,
    cost: 5_500,
  },
  {
    id: 22,
    imageUrl: IMAGES.hottub,
    product: "Hot Tub",
    count: 0,
    cost: 6_000,
  },
  {
    id: 23,
    imageUrl: IMAGES.luxurywine,
    product: "Luxury Wine",
    count: 0,
    cost: 7_000,
  },
  {
    id: 24,
    imageUrl: IMAGES.diamondring,
    product: "Diamond Ring",
    count: 0,
    cost: 10_000,
  },
  {
    id: 25,
    imageUrl: IMAGES.jetski,
    product: "Jet Ski",
    count: 0,
    cost: 12_000,
  },
  {
    id: 26,
    imageUrl: IMAGES.rolex,
    product: "Rolex",
    count: 0,
    cost: 15_000,
  },
  {
    id: 27,
    imageUrl: IMAGES.ford,
    product: "Ford F-150",
    count: 0,
    cost: 30_000,
  },
  {
    id: 28,
    imageUrl: IMAGES.tesla,
    product: "Tesla",
    count: 0,
    cost: 75_000,
  },
  {
    id: 29,
    imageUrl: IMAGES.monstertruck,
    product: "Monster Truck",
    count: 0,
    cost: 150_000,
  },
  {
    id: 30,
    imageUrl: IMAGES.ferrari,
    product: "Ferrari",
    count: 0,
    cost: 250_000,
  },
  {
    id: 31,
    imageUrl: IMAGES.singlefamilyhome,
    product: "Single Family Home",
    count: 0,
    cost: 300_000,
  },
  {
    id: 32,
    imageUrl: IMAGES.goldbar,
    product: "Gold Bar",
    count: 0,
    cost: 700_000,
  },
  {
    id: 33,
    imageUrl: IMAGES.mcdonalds,
    product: "McDonalds Franchise",
    count: 0,
    cost: 1_500_000,
  },
  {
    id: 34,
    imageUrl: IMAGES.superbowlad,
    product: "Superbowl Ad",
    count: 0,
    cost: 5_250_000,
  },
  {
    id: 35,
    imageUrl: IMAGES.yacht,
    product: "Yacht",
    count: 0,
    cost: 7_500_000,
  },
  {
    id: 36,
    imageUrl: IMAGES.abrams,
    product: "M1 Abrams",
    count: 0,
    cost: 8_000_000,
  },
  {
    id: 37,
    imageUrl: IMAGES.formula,
    product: "Formula 1 Car",
    count: 0,
    cost: 15_000_000,
  },
  {
    id: 38,
    imageUrl: IMAGES.apache,
    product: "Apache Helicopter",
    count: 0,
    cost: 31_000_000,
  },
  {
    id: 39,
    imageUrl: IMAGES.mansion,
    product: "Mansion",
    count: 0,
    cost: 45_000_000,
  },
  {
    id: 40,
    imageUrl: IMAGES.makeamovie,
    product: "Make a Movie",
    count: 0,
    cost: 100_000_000,
  },
  {
    id: 41,
    imageUrl: IMAGES.boeing,
    product: "Boeing 747",
    count: 0,
    cost: 148_000_000,
  },
  {
    id: 42,
    imageUrl: IMAGES.monalisa,
    product: "Mona Lisa",
    count: 0,
    cost: 780_000_000,
  },
  {
    id: 43,
    imageUrl: IMAGES.skyscraper,
    product: "Skyscraper",
    count: 0,
    cost: 850_000_000,
  },
  {
    id: 44,
    imageUrl: IMAGES.cruise,
    product: "Cruise Ship",
    count: 0,
    cost: 930_000_000,
  },
  {
    id: 45,
    imageUrl: IMAGES.nbateam,
    product: "NBA Team",
    count: 0,
    cost: 2_120_000_000,
  }
]

export default data;